### ISSUE TITLE
Multiple file not support

### ISSUE THREAD

**Issue by Lonor** [crazy-max/ghaction-upx#136]
#### Steps to reproduce this issue

1. Check out the below yaml configuraion

#### Expected behaviour

All the files are compressed.

#### Actual behaviour

An error occurred.

### Configuration

* Repository URL:  https://github.com/Lonor/elk-watcher
* Build URL:  https://github.com/Lonor/elk-watcher/runs/1725968775

```yml
      - name: UPX
        uses: crazy-max/ghaction-upx@v1
        with:
          version: latest
          file: release/watcher-linux-amd64 release/watcher-darwin-amd64 release/watcher-windows-amd64
          args: --best
```

### Logs

File to compress not found: release/watcher-linux-amd64 release/watcher-darwin-amd64 release/watcher-windows-amd64

### Other
I have checked the `main.ts`, and it just using one specified file:

```typescript
const file = core.getInput('file', {required: true});
```

The native `upx` command supports this functionality and path like `directory/*` which contains all the file in the directory. 
Thanks for this gh-action and I hope it available in the future version.
