### ISSUE TITLE
Add support for Darwin

### ISSUE THREAD

**Issue by wtfacoconut** [crazy-max/ghaction-upx#183]
### Behaviour
Using the action with a Max OS runner results in action failing due to Darwin not being supported.

#### Steps to reproduce this issue

1. just run the action with MacOS

#### Expected behaviour

It should work with MacOS runners.

#### Actual behaviour

The action fails

### Configuration

* Repository URL (if public): 
* Build URL (if public): 

```yml
name: Build and release
on:
  push:
    branches:
      - '**'
       
env:
  native_image_opts: --verbose -H:Log=registerResource:verbose
          
jobs:
...
  native_mac:
    name: native-image-mac
    needs: build
    runs-on: macos-12
    steps:
      - name: Check-out source code
        uses: actions/checkout@v3

      - uses: graalvm/setup-graalvm@v1
        with:
          version: '21.2.0'
          java-version: '11'
          components: 'native-image'

      - uses: actions/download-artifact@v3
        with:
          path: ./

      - name: Create native fcli
        run: native-image ${{ env.native_image_opts }} -jar ./artifact/fcli.jar fcli

      - name: Run UPX
        uses: crazy-max/ghaction-upx@v2
        with:
          version: latest
          file: fcli
...
```

### Logs

![image](https://user-images.githubusercontent.com/5297545/200999609-fb52159a-f53b-4a78-95e3-0d47afbe7c01.png)

**Comment by crazy-max** [comment]
UPX does not have any darwin binaries available: https://github.com/upx/upx/releases

What you can do is uploading the artifact and having another job running upx on `ubuntu-latest`:

```yaml
jobs:
...
  native_mac:
    name: native-image-mac
    needs: build
    runs-on: macos-12
    steps:
      - name: Check-out source code
        uses: actions/checkout@v3

      - uses: graalvm/setup-graalvm@v1
        with:
          version: '21.2.0'
          java-version: '11'
          components: 'native-image'

      - uses: actions/download-artifact@v3
        with:
          path: ./

      - name: Create native fcli
        run: native-image ${{ env.native_image_opts }} -jar ./artifact/fcli.jar fcli

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: fcli
          path: fcli

  upx:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: fcli
          path: .
      
      - name: Run UPX
        uses: crazy-max/ghaction-upx@v2
        with:
          version: latest
          file: fcli
```
